version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: localize-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: localize
    volumes:
      - mongodb_data:/data/db
    networks:
      - localize-network

  redis:
    image: redis:7-alpine
    container_name: localize-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - localize-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Redis Commander for GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: localize-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - localize-network
    depends_on:
      - redis

volumes:
  mongodb_data:
  redis_data:

networks:
  localize-network:
    driver: bridge